puppetlabs/clj-parent

project.clj
This commit adds a dependencies section that includes clojure.
This won't be inherited by child projects, but having it here
allows us to run `lein test` to just ensure that the project
is parseable.  It also inherits the clojure version from the
`managed-dependencies` section, so we get some basic smoke
testing of the inheritance.
=> (SERVER-1494) Add smoke test

CHANGELOG.md, project.clj
This commit updates the jvm-ssl-utils dependency from 0.8.1 to 0.8.2 and
updates the CHANGELOG.md for the 0.1.4 - 0.1.7 releases.
=> (MAINT) Update jvm-ssl-utils to 0.8.2, prep for 0.1.7 release

CHANGELOG.md, project.clj
Updates jdbc-util to 0.5.0
Updates dujour-version-check to 0.1.8
Updates Changelog for a 0.1.8 release.
=> (maint) update jdbc-util / dujour-version-check

CHANGELOG.md, project.clj
This commit adds clojurescript to the parent project.  This is
necessary in order to make sure that pe-puppet-server-extensions
and pe-puppetserver agree on what version of clojurescript to use.
=> (PE-18217) Add clojurescript and prep CHANGELOG for 0.2.3

project.clj
These are needed for use by orchestrator and pcp-broker.
=> (maint) Add trapperkeeper-metrics and ring-defaults

project.clj
This commit updates the clj-http-client dependency which now
automatically adds the accept-language header to outgoing requests.
=> (maint) Update clj-http-client dependency to 0.7.0

CHANGELOG.md, project.clj
This commit bumps:
* `puppetlabs/i18n` to 0.5.1 to take advantage of some recent
improvements around workflows / CI support.
* `trapperkeeper-metrics` to 0.5.0 to fix a bug in the v1 metrics
HTTP endpoint, as well as add the new jolokia-based v2 metrics
endpoint.
* `trapperkeeper-status` to 0.7.0 to add cpu/gc metrics, and add
service names and version numbers to relevant places in the log
output.
=> (MAINT) Prep for 0.3.0 release.

project.clj
This includes some websockets-related changes that PCP will benefit
from.
=> (maint) bump tk-jetty to 1.6.0

project.clj
Update trapperkeeper-scheduler to 0.1.0 to take advantage of new
group-id collections and potential `after` memory leak.
=> (maint) update trapperkeeper-scheduler to 0.1.0

project.clj
This commit bumps the trapperkeeper-status dependency from 0.7.0 to
0.7.1.
=> (MAINT) Bump tk-status to 0.7.1

CHANGELOG.md, project.clj
This commit bumps the tk-jetty9 version from 1.6.0 to 1.7.0 and updates the CHANGELOG.md file for an 0.3.3 release.
=> (MAINT) Bump tk-jetty9 to 1.7.0 and prep for 0.3.3 release

project.clj
Logback 1.1.8 is strictly necessary to fix this bug (according to the changelog/ticket but 1.1.9 is the latest by the time work was started. 1.1.9 increases the size of it's threadpool to hopefully improve configuration scanning.
=> (TK-428) Upgrade logback for totalLogSize rotation fix

CHANGELOG.md, project.clj
This commit bumps the puppetlabs/http-client dependency from 0.7.0 to
0.8.0 and updates the CHANGELOG.md file for the 0.4.1 release.
=> (MAINT) Bump http-client to 0.8.0 and prep for 0.4.1 release

project.clj
This PR updates the trapperkeeper-metrics dependence to 1.0.0 in order to pull in changes such as support for graphite exporting. 
Note: The tk config format for tk-metrics has changed in version 1.0.0 and will require projects which use tk-metrics to be updated to the new format.
This will probably result in a clj-parent 0.5.0 release because of the tk-metrics bump
* Update tk-metrics to 1.0.0 to pull in the functionality previously found in
pe-tk-metrics, including graphite exporting support
* Remove pe-tk-metrics, since the functionality was ported to OSS tk-metrics
* Add metrics-core since multiple projects reference it now
=> (SERVER-1721) Update tk-metrics to 1.0.0

CHANGELOG.md, project.clj
- Adds dependency for io.dropwizard.metrics/metrics-core 3.1.2
- Updates puppetlabs/trapperkeeper-metrics to 1.0.0
- Removes dependency on puppetlabs/pe-trapperkeeper-metrics
=> (MAINT) Update version for 0.5.0 release

project.clj
This commit picks up changes to clj-i18n that removes the use and generation of English bundles if an en.po is not present. Opting instead to fallback to the POT as intended. This work also fixes a bug surfacing GNU gettext treatment of empty strings. Prior to this commit, empty strings would display the header of the POT file. Now an externalized empty string displays an empty string.
=> (maint) Bump clj-i18n to 0.7.1

project.clj
circleci/clj-yaml is a maintained version of the original clj-yaml
project that was last updated in 2012. This commit updates the
dependency to circleci's fork.
=> (maint) Update clj-yaml to a maintained version

project.clj
There have been a few cases where rbac-client has fallen behind in
project dependencies. This commit adds rbac-client to clj-parent so that
projects that are up to date with their parent release will also be up
to date with rbac-client.
=> (maint) Add rbac-client to clj-parent

project.clj
Several projects use the rbac-client test jar. This commit adds that to the
dependency list so that these probjects no longer need to specify a version
for the test jar.
=> (maint) Add rbac-client test jar to dependency list

project.clj
This commit bumps the org.yaml/snakeyaml version from 1.13 to 1.18, for
compatibility with the version used in the latest JRuby, 9.1.8.0.  Per
issue #323 in the snakeyaml bitbucket project, 1.18 does have some minor
breaking changes (method signature changes).  None of the changes
appear to be exposed / utilized from clj-yaml.  The next clj-parent
release which has this bump should probably be at least a Y version,
though, for visibility.
=> (SERVER-1630) Bump snakeyaml version to 1.18

project.clj
Cheshire 5.7.1 fixes an issue with streaming large lazy-seqs. The head
of the seq is held onto which results in keeping the entire lazy-seq
in memory. This commit also bumps the jackson library version to match
the version cheshire uses.
=> (PDB-3467) Bump to cheshire 5.7.1

project.clj
This updates the rbac-client to 0.7.0 as part of PE-20265.
=> (PE-20265) update rbac-client to 0.7.0

CHANGELOG.md, project.clj
This updates jdbc-util 1.0.0
In addition HikariCP 2.6.1 is added as a new dependency.
This change means that clj-parent will require jdk8 if jdbc-util or Hikari 2.6.1 is used.
=> (maint) update jdbc-util 1.0.0 bump version 0.8.0

project.clj
I've been running into dependency conflicts with jetty-websockets
versions. I moved all jetty components in trapperkeeper-webserver-jetty9
here so they use the same version.
=> (PCP-741) Move jetty version to clj-parent

project.clj
metrics-clojure is used by pcp-broker, puppetdb, and other PE services.
Add it to avoid conflicts between those projects.
=> (maint) Add metrics-clojure 2.6.1 as a new dependency

project.clj
This commit adds org.ow2.asm/asm-all.  This is being included to help
mitigate conflicts which arise between the version of asm-all (4.2)
that org.clojure/core.async (0.2.391) pulls in transitively via
org.clojure/tools.analyzer.jvm (0.6.10) and what JRuby (1.7.26+) uses,
asm-all (5.0.3).
=> (MAINT) Add asm-all dependency

project.clj
This updates our dropwizard dependency to the latest release to pick up
a fix for a memory leak.
This version of dropwizard also provides native support for blacklisting
metrics attributes (eg. "p99", "m15").  Any downstream projects that
have implemented their own GraphiteReporter for blacklisting
functionality can now move to using the built in feature.
---
I created a version of [Puppet Server 5](http://builds.delivery.puppetlabs.net/puppetserver/5.0.0.master.SNAPSHOT.2017.06.06T2339/repo_configs/rpm/) using this code and attempted to replicate the [memory & cpu testing](https://tickets.puppetlabs.com/browse/SERVER-1735?focusedCommentId=449039&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-449039) that we did when we introduced this library. The …
=> (TK-442) Update io.dropwizard.metrics/metrics-core to 3.2.2

project.clj
jdbc-util had a potential uncaught exception during migrations on
replicas.  This updates to a version that correctly catches and
logs the exception.
=> (maint) update jdbc-util to 1.0.1

project.clj
Bumps jdbc-utils to fix "WARN  [c.z.h.HikariConfig] The initializationFailFast propery is deprecated, see initializationFailTimeout"
=> (maint) jdbc-utils 1.0.2

project.clj
Staging this PR for now, this is blocked on actually releasing https://github.com/puppetlabs/clj-http-client/pull/74
=> (TK-443) Update clj-http-client

project.clj
This patch updates ring-defaults to a newer release which no longer drags in
an ancient version of the Java Servlet API.
=> (maint) Update ring-defaults to 0.3.0

CHANGELOG.md, project.clj
Both the puppetdb and orchestrator projects have this as a dependency.
=> (ORCH-1788) Add honeysql to project.clj + bump to 1.3.0

CHANGELOG.md, project.clj
This version of tk-jetty9 includes code to perform runtime refreshes of
the CRL.
=> (TK-452) Update tk-webserver-jetty9 to 2.1.0

CHANGELOG.md, project.clj
Update the rbac-client depdendency to 0.7.1
Update the CHANGELOG in anticipation of a version 1.4.2 release
=> (maint) update rbac-client to 0.7.1

CHANGELOG.md, project.clj
This transitive dependency has been observed to conflict between
pe-puppetdb-extensions and orchestrator. This version is the most recent
of the conflicting versions, and using it with pe-puppetdb-extensions
does not appear to cause any overt problems in PuppetDB.
=> (maint) Add jackson-databind @ 2.9.0

CHANGELOG.md, project.clj
This commit bumps the rbac-client version for the project to include the new method added to the consumer service, which allows service calls for permitted instances with token authentication. 
The changes also bump the clj-parent version with a minor increase, as the clj-rbac-client changeset is a breaking change to rbac because it updates the RbacConsumerService protocol.
=> (PE-23159): bumping rbac client version for consumer change

CHANGELOG.md, project.clj
Update the version of puppetlabs/jdbc-util to 1.0.3 which includes dupdates for the postgres driver and HikariCP.
Update the changelog in preparation for a release.
=> (maint) update puppetlabs/jdbc-util to 1.0.3

project.clj
This commit updates bidi to 2.1.3, which contains a fix for a bug when
parsing URIs with spaces. It also updates comidi to a version compatible
with the new bidi.
=> (SERVER-1954) Update bidi and comidi

CHANGELOG.md, project.clj
These contain changes to make them work with Java 9.
=> (maint) Update trapperkeeper and kitchensink

CHANGELOG.md, project.clj
This update of tk-jetty9 allows POST reqest responses to be gzipped when
using Jetty 9.4. This fixes a regression from the 1.x branch of
tk-jetty9, which uses an older version of Jetty.
=> (SERVER-2118) Update tk-jetty9 to 2.1.2

CHANGELOG.md, project.clj
This updates jdbc-util to 1.1.1 to address some issues with pglogical
and migratus migrations.
=> (PE-23667) update jdbc-util to 1.1.1 and changelog

CHANGELOG.md, project.clj
The JrJackson gem allows Jackson to be used from Ruby and requires
Jackson's Afterburner module. This commit brings that in and updates all
other Jackson libraries to 2.9.4, the latest release.
=> (SERVER-2098) Add afterburner and update jackson to 2.9.4

CHANGELOG.md, project.clj
This updates to clojure 1.9, and updates all the clojure space
dependencies to the latest.
In addition, it updates ring-mock to the new repo.
=> (maint) update to clojure 1.9

project.clj
This commit bumps the janino version from 2.7.z to 3.0.z in order to keep pace
with Logback 1.2.
=> (maint) Bump janino version to 3.0.8

CHANGELOG.md, project.clj
Update jdbc-util, which has changes to the delayed pool initialization and update the changelog
=> (maint) update jdbc-util to 1.2.0 and changelog

CHANGELOG.md, project.clj
This updates clj-rbac-client to 0.8.3 to add the `subject` method to
the consumer service, and the remote client implementation of it.
=> (PE-24735) update clj-rbac-client to 0.8.3

CHANGELOG.md, project.clj
This updates jdbc-util to 1.2.2 which changes the way the deferred
init and migrations are handled to make them more robust.  It includes
a new version of migratus and java.jdbc.
=> (maint) update jdbc-util to 1.2.2

project.clj
This updates rbac-client to 0.9.1 to bring in a new function into the RBAC consumer service.
=> (PE-24735) update clj-rbac-client to 0.9.1

CHANGELOG.md, project.clj
This updates jdbc-util to 1.2.3 to deal with some issues seen in testing.
Specifically, a partial migration/deadlock can occur if the pool is closed
while the migrations are running.  This updates the close-after-ready behavior
to specifically wait for a safe point prior to closing the pool.
=> (PE-24859) update jdbc-util to 1.2.3

CHANGELOG.md, project.clj
This updates clj-parent to bring in new versions of dependencies it
uses.  It also updates the changelog to reflect those changes.
=> (maint) update clj-parent and update changelog

CHANGELOG.md, project.clj
This updates clj-parent to bring in new versions of dependencies it
uses. It also updates the changelog to reflect those changes.
=> (maint) update clj-ldap to 0.2.0 and changelog

CHANGELOG.md, project.clj
This eliminates the two remaining places where puppetdb was ahead of clj-parent 2.1.
=> (maint) Update schema and compress to latest z versions

project.clj
Liberator can be made Java 9/10 compatible with the appropriate flags,
but without them, version 0.12 is not 9/10 compatible. Also there will
be no flag available to make liberator 0.12 compatible with Java 11.
This changes liberators version to the minimum required for 9/10
compatiblility without additional flags and the minimum required for
Java 11 compatibility.
=> (PDB-3942) Raise liberator dependency to java 9 compatible

CHANGELOG.md, project.clj
This is necessary due to the use of dropwizards 3.2.2. As you can see
from metrics-clojure/metrics-clojure@f5b2e92 when upgrading to 3.2.2
metrics-clojure needed a change to `time-fn!` and since clj-parent
already uses dropwizards 3.2.2, using the old version of
metrics-clojure was causing `time-fn!` to break.
=> (PDB-3942) Update metrics-clojure to 2.10.0

project.clj
Medley is a dependency of compojure, which is a dependency of comidi. Probably all of our webservice require it transitively. Puppet Server is currently pulling in 0.7.x and the jump between it and 1.0 should contain no breaking changes. However the 0.6 and 0.7 bumps contained breaking changes according to their docs https://github.com/weavejester/medley#breaking-changes so be aware when upgrading.
This upgrade is needed to remove:
```
WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: medley.core, being replaced by: #'medley.core/boolean?
```
/cc @MikaelSmith @steveax @jonathannewman @rbrw (no idea who all should be pinged on this)
=> (maint) Add medley

CHANGELOG.md, project.clj
clj-http-client fixes an issue were malformed content-type headers
could result in a blank response.  It also adds two configuration
values that can be used for persistent clients to allow the total
number of connections allowed through the client, as well as the
total number of connections per route through the client.
=> (maint) update clj-http-client to 1.0.0

CHANGELOG.md, project.clj
This updates the trapperkeeper-scheduler to version 1.0.0 to replace
the use of at-at with the quartz scheduler.
Update changelog for 2.3.4 release
=> (maint) update tk-scheduler to 1.0.0 and prepare for 2.3.4 release

CHANGELOG.md, project.clj
This updates clj-rbac-client to 0.8.4 to allow more simultaneous connections to rbac and activity service.  It also updates the changelog in preparation for a release.
=> (maint) update clj-rbac client and prepare for 1.7.6 release

CHANGELOG.md, project.clj
This updates clj-rbac-client to 0.9.2, which increases the number of simultaneous requests to rbac and activity services from 2 to 20 each.
It also updates the CHANGELOG in preparation of the 2.3.5 release.
=> (maint) update clj-rbac-client to 0.9.2 and prepare for 2.3.5 release

project.clj
This update brings in a newer version of Jetty, which has fixes for some
security vulnerabilities.
=> (TK-472) Update tk-jetty9 to 2.3.0

CHANGELOG.md, project.clj
Updates to trapperkeeper-scheduler 1.0.1 and updates the changelog.
=> (maint) update tk-scheduler, prepare for release

CHANGELOG.md, project.clj
This updates tk-scheduler to 1.1.0 that adds a new interface for interspaced jobs.  
It also updates project.clj and CHANGELOG in prep for a 2.4.0 release.
=> (PE-25389) update tk-scheduler to 1.1.0, prepare for 2.4.0 release

CHANGELOG.md, project.clj
As part of integrating the rbac client into tk-auth, we needed to open
source the library. This commit bumps the version of clj-rbac-client to
the new public release.
=> (TK-475) Update rbac client to public version

CHANGELOG.md, project.clj
This was updated in kitchensink when doing the Java 9+ work but because
it wasn't updated in clj-parent it doesn't look like most projects were
actually using the dependency at that version.
The previous version of dynapath (0.2.4) would decide whether or not it
could use the APIs exposed in Java 8 and if not only use the ones
exposed in Java 9+. It would make that decision at compile time however
so projects AOTed on Java 8 could not be ran on new Java versions. 0.2.5
moved the check to runtime rather than compile time, and 1.0.0 removes
the check completely and only extends the classes exposed in 9+.
=> (maint) Update dynapath to 1.0.0 and Clojure to 1.10

CHANGELOG.md, project.clj
This version of tk-auth adds the ability to specify rules based on RBAC
permissions. It is NOT a breaking change; we moved the library to 1.0.0
to establish clear semver for tk-auth from here on out.
=> (TK-474) Update tk-auth to 1.0.0

project.clj
This version contains an update to BouncyCastle, fixing some security
vulnerabilities.
=> (SERVER-2431) Update jvm-ssl-utils to 1.0.2

CHANGELOG.md, project.clj
This updates trapperkeeper-webserver-jetty9 to 2.4.0 which includes the new disconnect function to allow disconnecting a websocket.
=> (PCP-862) Update trapperkeeper-webserver to 2.4.0

CHANGELOG.md, project.clj
This updates trapperkeeper-webserver-jetty9 to 2.4.1 which only disconnects a connection if the session is not null
=> (PCP-862) Update tk-webserver-jetty9 to 2.4.1

CHANGELOG.md, project.clj
This bumps trapperkeeper-webserver-jetty9 to 2.4.1 which includes a `disconnect` function to disconnect from websocket connections
=> (PCP-862) Bump tk-webserver-jetty9

project.clj
This was open sourced for trapperkeeper-authorization use and we need to
use a version from after it was open sourced in puppetserver. This has
only minor changes.
=> (maint) Bump rbac-client to publicly published version

CHANGELOG.md, project.clj
The analytics-client was recently open-sourced, so this commit pulls it
into clj-parent, to help managing its version across projects easier.
=> (SERVER-2522) Add analytics-client

CHANGELOG.md, project.clj
This adds support for the mainline nrepl project and maintains backwards
compatibility with the legacy version living in org.clojure. This is part of a
series of changes to support nrepl/nrepl in trapperkeeper.
=> (orch-2282) Add support for nrepl/nrepl in parallel w/ org.clojure/tools.nrepl

project.clj
This is part of ongoing work to move to a more current version of nrepl; this involves changes to clj-parent, trapperkeeper, orchestrator and pe-orchestration-services.
This should not be merged until after https://github.com/puppetlabs/trapperkeeper/pull/280 is merged.
=> (ORCH-2282) Update to tk 2.0.0 as part of supporting nrepl/nrepl

CHANGELOG.md, project.clj
This update contains better error surfacing.
=> (maint) Update trapperkeeper to 2.0.1

project.clj
Update to the latest minor release, which includes a fix for a
notable performance regression.
=> (maint) Update clojure to 1.10.1

project.clj
Snapshots should publish to artifactory, not the old Nexus server
=> (maint) replace broken snapshot deploy repo

CHANGELOG.md, project.clj
This addresses an issue where names with extended characters would
be displayed as base64 encoded strings instead of the name itself.
=> (PE-26836) update clj-ldap to 0.2.1

CHANGELOG.md, project.clj
This merges in a change to clj-ldap that fixes an issue with incorrect base64 encoding of parameters that didn't need to be encoded.
=> (maint) merge 1.7.x -> master

project.clj
This is a breaking change that requires consumers of ssl-utils to
specify their own version of bouncycastle (which was previously brought
in for them). They are now also free to choose between FOSS and FIPS
bouncy castle versions.
=> (maint) Include FIPS compatible ssl-utils

project.clj
This is the first release in the TK Jetty 3.x series and includes
updated cipher suite defaults and the removal of the so-linger-seconds
option.
=> (maint) Take up trapperkeeper-webserver-jetty9 3.0.1

project.clj
me.raynes/fs is unmaintained, though the project has been forked and
taken over by the clj-commons community. The API has not changed but
they are reactively updating dependencies as needed.
When we upgraded apache's commons/compress to 1.18 we broke raynes'
fs because it dependend on compress bringing in xz. This is only
apparent when require me.raynes.fs.compression.
Because this exposes the same namespaces and vars as raynes' I've chosen
to replace raynes with it. Otherwise which project was loaded would be
unspecified.
This will require all consumers to update their dependencies from
`[me.raynes/fs]` to `[clj-commons/fs]` but should require zero code
changes.
=> (maint) Replace me.raynes/fs with clj-commons/fs

project.clj
clj-commons has taken over ownership of clj-yaml and it behooves us to
use their maintained version of it.
This replaces circleci's version to require users to upgrade their
dependencies since having both artifact groups causes undefined behavior
when loading (they provide the same namespaces).
This is the same approach to how we are upgrading me.raynes/fs.
=> (TK-482) Use clj-commons/clj-yaml instead of circleci

CHANGELOG.md, project.clj
This update further restricts the default list of available cipher
suites.
=> (TK-484) Update tk-jetty9 to 4.0.0

CHANGELOG.md, project.clj
This updates jdcb-util to 1.2.5 to address issues with replicas creating
the migration table, when it is assumed that replicas will be a read-only
relationship with the database.
Also update changelog in preparation for release.
=> (PE-27018) update jdbc-utl to 1.2.5

project.clj
Updates to bc-fips 1.02, which supports JDK 11
Adding bctls-fips 1.0.9, which is necessary to do proper TLS serving
=> (PE-26658) Update version of bc fips

CHANGELOG.md, project.clj
Updates to the versions that properly support FIPS
=> (PE-26658) update clj-http-client & tk-jetty9

CHANGELOG.md, project.clj
This version has improved error handling.
=> (PE-27497) Update tk-filesystem-watcher to 1.1.1

CHANGELOG.md, project.clj
This adds support for the multithreaded key for JRubyConfig.
=> (SERVER-2360) Update jruby-utils to 2.3.1

project.clj
This update downgrades JRuby to 9.2.8.0 to avoid a bug in 9.2.9.0.
=> (SERVER-2674) Update jruby-utils to 2.3.2

project.clj
PostgreSQL JDBC driver has a bug where the isValid() call on a
connection does not respect timeouts. This causes our connection pool to
not detect a dead connection, which will eventually exhaust our
connection pool entirely. See pgjdbc/pgjdbc#1557
=> (PDB-4579) fix connection tests

project.clj
Update taoensso/nippy and taoensso/encore to remove warnings:
WARNING: pos-int? already refers to: #'clojure.core/pos-int? in namespace: taoensso.encore, being replaced by: #'taoensso.encore/pos-int?
WARNING: bytes? already refers to: #'clojure.core/bytes? in namespace: taoensso.encore, being replaced by: #'taoensso.encore/bytes?
=> (PDB-4255) update taoensso libs to remove warnings

CHANGELOG.md
A few releases have been done and the changelog hasn't been updated.
In order to keep the changelog relevant, and allow someone to know
what has changed with an at-a-glance look, this adds the missing
updates.
=> (maint) update changelog

CHANGELOG.md, project.clj
This updates http-client to 1.1.3, which includes improvements to
prevent clojure being unable to resolve symbols due to class loader
changes in java 11.  Specifically when service were reloaded, some
were unable to resolve the correct class constructor methods.  The
change in 1.1.3 removes that ambiguity with type hints.
In a separate commit, the changelog is updated in preparation for a new release.
=> (PE-27189) update http-client to 1.1.3

CHANGELOG.md, project.clj
=> (maint) Bump jruby-utils to 3.0.4

CHANGELOG.md, project.clj
update tk-filesystem-watcher to ignore lock directories that disappear when registering
=> (PE-27497) Bump tk-fs-watcher to 1.1.2

CHANGELOG.md, project.clj
This update contains a fix for type ambiguity in Java 11.
=> (SERVER-2734) Update tk-jetty9 to 4.0.3

CHANGELOG.md, project.clj
Update tk-metrics to 1.2.1 and update the change log.
=> (maint) bump tk-metrics to 1.2.1, prepare for release

CHANGELOG.md, project.clj
1.2.1 was only released to artifactory, 1.2.2 is available on clojars.
=> (maint) Bump tk-metrics to clojars' version

CHANGELOG.md, project.clj
This update contains a new function for doing atomic file writes.
=> (SERVER-2565) Update kitchensink to 3.1.0

CHANGELOG.md, project.clj
We found a potential bug in JRuby 9.2.11.1, so this commit updates
jruby-utils to a version with JRuby rolled back to 9.2.8.0.
=> (SERVER-2793) Downgrade JRuby to 9.2.8.0

CHANGELOG.md, project.clj
We're going to give this another try now that the last release went out.
=> (SERVER-2793) Bump JRuby back to 9.2.11.1

CHANGELOG.md, project.clj
This update deprecates the v1 metrics endpoint.
=> (TK-486) Update tk-metrics to 1.2.3

CHANGELOG.md, project.clj
This commit updates i18n to 0.9.0. This is the latest version and what puppetdb
is already using.
=> (maint) Update i18n to 0.9.0

CHANGELOG.md, project.clj
This commit bumps ring middleware to 1.1.0, to pull in a couple new wrappers for use in console-ui.
=> (PE-28654) bump ring middleware version

CHANGELOG.md, project.clj
This commit bumps bctls-fips to 1.0.10 to ensure we're on the latest version
in the LTS.
=> (SERVER-2801) Bump bouncycastle/bctls-fips to 1.0.10

CHANGELOG.md, project.clj
=> (maint) Bump ring-middleware to 1.2.0

CHANGELOG.md, project.clj
This updates clj-rbac-client to 1.0.0, which adds support for the upcoming "v2" submission endpoint.  If the service does not support the v2 endpoint, the client will gracefully roll back to use the v1 endpoint.
Also the changelog was updated with the intent of creating a new release.
=> (PE-29720) update clj-rbac-client and changelog

CHANGELOG.md, project.clj
This update contains JRuby 9.2.13.0, which has some security fixes.
=> (SERVER-2853) Update jruby-utils to 3.2.0

CHANGELOG.md, project.clj
This update adds a new method to revoke multiple certs at once.
=> (SERVER-2859) Update jvm-ssl-utils to 1.1.0

CHANGELOG.md, project.clj
This update adds a function to revoke multiple certificates at once.
=> (SERVER-2859) Update jvm-ssl-utils to 3.1.0

CHANGELOG.md, project.clj
This commit updates clj-kitchensink to 2.6.0, which adds a function to
atomically write files.
=> (SERVER-2863) Update clj-kitchensink to 2.6.0

CHANGELOG.md, project.clj
Brings in the new status service which includes additional JVM info regarding memory pools
=> (maint) Merge 1.7.x into main

CHANGELOG.md, project.clj
This updates clj-rbac-client to 1.1.0, which contains deprecations
for functions that contain harmful language, and adds a new function
to replace a deprecated method.
Also prepare for the 4.6.4 release.
=> (PE-29997) update clj-rbac-client to 1.1.0

CHANGELOG.md, project.clj
This updates the clj-rbac-client version to 1.1.1, which includes a fix for a bug introduced in the 1.1.0 version.
=> (PE-30059) update clj-rbac-client to 1.1.1

CHANGELOG.md, project.clj
This update has a function for retrieving the message from a response
status.
=> (SERVER-2780) Update clj-http-client to 1.2.0

CHANGELOG.md, project.clj
This commit updates clj-kitchensink 3.1.1 which changes the open-port-num
function to select a port in the 16384 - 32767 range. This should decrease port
binding collisions in some cases.
=> (maint) update clj-kitchensink to 3.1.1

CHANGELOG.md
=> (maint) prepare for 4.6.7 release

CHANGELOG.md, project.clj
This sets the ring-middleware version to 1.3.0, which updates `wrap-add-cache-headers` to use
the "no-store" cache-control directive instead of "private, max-age=0, no-cache"
=> (PE-30230) update ring-middleware version

CHANGELOG.md, project.clj
This updates trapperkeeper-scheduler to 1.1.3 to update the quartz library to a more recent z version and to add protection from scheduling null values for the scheduled functions.
=> (maint) update tk-scheduler to 1.1.3

CHANGELOG.md, project.clj
=> (maint) Upgrade JRuby to 9.2.14.0

CHANGELOG.md, project.clj
Upgrades to the current latest release of https://github.com/lightbend/config with an upgrade to our wrapper library. Primarily improves referencing environment variable lists.
=> (maint) Update typesafe config

CHANGELOG.md, project.clj
This updates jetty and bouncy castle.
No issues with either in any puppetserver project.
=> (PE-30976) Security updates

CHANGELOG.md, project.clj
This commit updates our jackson dependencies to the latest version to
fix a known security vulnerability.
=> (PE-31011) Update jackson to 2.12.1

CHANGELOG.md, project.clj
This commit bumps our ring-servlet dependency back to 1.5.1. This is the latest
release that doesn't cause failures in our beaker tests. We will ultimately need
to bump this back, but for now we need to get CI green.
=> (SERVER-2948) Bump ring-servlet back to known good version

CHANGELOG.md, project.clj
This fixes things for file-sync, overriding the version that comes in with `commons-validator`.
I also examined the deps in pe-puppetdb-extensions, and it looks like this also overrides what shiro brings in.
=> (PE-30976) Update commons-beanutils to 1.9.4

CHANGELOG.md, project.clj
To fix the CVE this has a potentially breaking change to the freeze and
thaw methods. If a class you need to thaw is not on the allowlist you
will need to bind a new set of allowed java classes to thaw. It would
look something like the example below.
```
(binding [nippy/*thaw-serializable-allowlist* #{"org.joda.time.DateTime"}]
(nippy/thaw (Files/readAllBytes path)))
```
Upgrading to 2.15.3 would have also negated the CVE, but 2.15.0 had a
breaking change even though it was a y release. And by going to the 3.y
versions we can use the allowlist instead of the initial whitelist that
they added in 2.15.0 and later renamed.
=> (PDB-5000) Update nippy to 3.1.1

CHANGELOG.md, project.clj
This reverts commit 49a95882e6b97cd456c14d0a11496fa3c7df3436.
We have made the necessary updates to take up this new version of ring-servlet.
=> Revert "(SERVER-2948) Bump ring-servlet back to known good version"

CHANGELOG.md, project.clj
The commons-compress bump fixes a known CVE. We also bump clj-commons/fs
since that library also depends on commons-compress. Note that our
commons-compress version matches what's in clj-commons/fs.
Signed-off-by: Enis Inan <enis.inan@puppet.com>
=> (PE-31016) Bump commons-compress and clj-commons/fs

CHANGELOG.md, project.clj
To bring in the addition of the base-type function for
parsing Content-Type headers.
=> (PE-31121) update clj-kitchensink to 3.1.3

CHANGELOG.md
=> (maint) prep for 4.6.18 release

CHANGELOG.md, project.clj
This contains fixes for several CVEs.
=> (PE-31797) Update tk-jetty9 to 4.1.5

CHANGELOG.md, project.clj
This brings in JRuby 9.2.17.0, which is a maintenance update.
=> (SERVER-3007) Update jruby-utils to 3.2.2

CHANGELOG.md, project.clj
This update contains more advanced functions for generating and
validating CRLs.
=> (SERVER-2550) Update jvm-ssl-utils to 3.2.0

CHANGELOG.md, project.clj
This update fixes a compatibility issue between FOSS and FIPS Bouncy
Castle, as well as adds some new extension utilities.
=> (maint) Update jvm-ssl-utils to 3.2.2

CHANGELOG.md, project.clj
This commit updates clojurescript to the latest release in order to resolve CVEs
in transitive dependencies.
=> (maint) Update clojurescript to 1.10.866

project.clj
We recently updated BC's FOSS releases (in January), at the time of
upgrade BC's updates to their FIPS libraries had not been revalidated.
They now are (passed in April) and this patch updates our FIPS libraries
to the latest release. They should be covered by certificate #3514, see:
https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3514
=> (maint) Update BC FIPS to latest

CHANGELOG.md, project.clj
This version contains support for EC private keys with an EC parameter
block in the PEM file.
=> (SERVER-3016) Update jvm-ssl-utils to 3.3.0

CHANGELOG.md, project.clj
This update fixes the following CVEs: CVE-2021-36090, CVE-2021-35515,
CVE-2021-35516, CVE-2021-35517.
=> (SEC-739) Update commons-compress to 1.21

CHANGELOG.md, project.clj
This commit updates trapperkeeper-webserver-jetty9 to 4.1.8 to bring
in Jetty v9.4.43 to resolve CVE-2021-34429.
=> (SEC-745) update Jetty to 9.4.43 (CVE-2021-34429)

CHANGELOG.md, project.clj
i18n 0.9.2 adds some improvements to PuppetDB's query performance. This improvements are detailed in https://github.com/puppetlabs/clj-i18n/pull/49.
Also tested if this introduces problems with restarting PuppetDB via SIGHUP and it works fine with JAVA 8. 
This is not the case with JAVA 11, but TK services restart also fails with the  current version of i18n.
=> (PDB-5206) update i18n to 0.9.2 which has the fixes made in PDB-5190

CHANGELOG.md, project.clj
This commit updates trapperkeeper-metrics to 1.4.1, which includes Jolokia
1.7.0, a routine maintenance bump that cleans up some reflective accesses that
trigger warnings in Java 9 and newer.
=> (maint) Bump tk-metrics to 1.4.1

CHANGELOG.md
This updates the changelog to indicate the most recent changes
will be in 4.6.30.
=> (maint) update changelog in preparation for release

CHANGELOG.md, project.clj
This version correctly pulls in Bouncy Castle as a "provided" dep,
allowing it to be swapped out in FIPS mode.
It also reintroduces the previously-reverted jolokia bump.
=> (maint) Update tk-metrics to 1.4.3

CHANGELOG.md, project.clj
This adds support for a referrer-policy header wrapper to augment
responses with the referrer-policy on a given route.
=> (PE-32193) update ring-middleware to 1.3.1

CHANGELOG.md, project.clj
This commit bumps trapperkeeper-webserver-jetty9 to 4.2.0, which includes
support for TLS 1.3 by default.
=> (TK-494) Bump tk-jetty9 to 4.2.0

CHANGELOG.md, project.clj
This commit bumps trapperkeeper-webserver-jetty9 to 4.2.1, which includes
TLS 1.3 support for FIPS.
=> (maint) Bump tk-jetty9 to 4.2.1

CHANGELOG.md, project.clj
This commit bumps comidi to 0.3.3, which doesn't include any new content, but
should clear up false positives from the Snyk security scanner.
=> (maint) Bump comidi to 0.3.3

CHANGELOG.md, project.clj
This updates cheshire to version 5.10.1 which contains updated
dependency versions of jackson, and also contains some optimizations
to remove doseq in favor of reduce.  https://github.com/dakrone/cheshire/commit/7040a4a099c3e8ef6c41fc37b78a33e9b507edc3
=> (SEC-940) update cheshire to version 5.10.1

CHANGELOG.md, project.clj
Pull in security fixes in 1.x series.
=> (SEC-941) Update honeysql to latest 1.x series

CHANGELOG.md, project.clj
Version 1.2.3 of logback is vulnerable to https://security.snyk.io/vuln/SNYK-JAVA-CHQOSLOGBACK-1726923
This updates the logback version to 1.2.7 which is no longer vulnerable.
=> (maint) update logback to 1.2.7 to address security issues

CHANGELOG.md, project.clj
This updates the changelog and release version in preparation of
the 4.9.0 release.  The "Y" was bumped because the honeysql changes
contain breaking changes to some of the interfaces.
=> (maint) prepare for 4.9.0 release

project.clj
This updates logback to 1.2.9 to address the issues described in
https://nvd.nist.gov/vuln/detail/CVE-2021-42550
=> (maint) update logback to 1.2.9

CHANGELOG.md, project.clj
This updates jackson to 2.12.6 to address a potential DoS attack
when deserializing JSON content.
see https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698 for
more details.
=> (maint) update jackson to 2.12.6

CHANGELOG.md, project.clj
This update brings improved TLS 1.3 support. Note that BC split some
utilities into a new separate jar, `bcutil` that is now also pulled in
as a transitive dependency, in addition to `bcprov`.
=> (SERVER-3135) Update bouncy-castle to 1.70

CHANGELOG.md, project.clj
This commit adds a dependency on honeysql 2.x, under the group ID
`com.github.seancorfield`. This allows us to depend on both honeysql 2.x and
honeysql 1.x as projects migrate from 1.x to 2.x. honeysql 2.x uses different
namespaces than honeysql 1.x, which will prevent any conflicts from depending
on both versions. Once all projects have migrated, the bare `honeysql`
dependency can be removed.
See https://github.com/seancorfield/honeysql/blob/develop/doc/differences-from-1-x.md
=> (maint) Add honeysql 2.x dependency

CHANGELOG.md, project.clj
This update pins jnr-posix to avoid a CVE.
=> (SERVER-3157) Update jruby-utils to 3.2.3

CHANGELOG.md, project.clj
This has some minor dependency updates (which clears up a Snyk warning),
and a potential perf increase.
Note that the snyk warning is getting picked up from a transitive dep (jackson-dataformat) that we override, so we're not actually vulnerable, but I was trying to clear up the "high" severity warnings for code-manager and this is the only one (besides the gettext license).
=> (maint) Update ring-json to 0.5.1

CHANGELOG.md, project.clj
This updates the postgres sql driver to address https://security.snyk.io/vuln/SNYK-JAVA-ORGPOSTGRESQL-2401816
=> (maint) update postgres sql driver to 42.3.3

CHANGELOG.md, project.clj
This updates cheshire from 5.10.1 to 5.10.2, to remove an unneeded dependency on jackson-databind.
https://github.com/dakrone/cheshire/pull/187
jackson-databind is a source of a lot of security issues and requires regular updates.
=> (maint) update cheshire to 5.10.2

CHANGELOG.md, project.clj
=> (maint) Update kitchensink to 3.2.0 and prepare 4.10.0 release

CHANGELOG.md, project.clj
=> (SERVER-2944) Bump ssl-utils to 3.4.1

CHANGELOG.md, project.clj
This version changes the default TLS protocols for the HTTP client to be 1.3 and 1.2, and removes 1.1 and 1.0. We are bumping the Y due to the potentially breaking change of removing old TLS protocols from http-client defaults. This enables TLSv1.3 on HTTP clients without having those settings exposed yet in config files for each component (see related tickets in epic https://tickets.puppetlabs.com/browse/PE-33171).
=> (PE-33177) Update http-client to 2.0.0

CHANGELOG.md, project.clj
This updates clojure to 1.11.1, and updates the various clojure tools
and data deps that are specified in clj-parent. Most hadn't been updated
since 2018.
=> (PE-33735) update clojure to 1.11.1, and update clojure deps

CHANGELOG.md, project.clj
This unpins a dependency that was causing pedantic conflicts.
=> (maint) Bump jruby-utils to 4.0.1

CHANGELOG.md, project.clj
This updates tk-jetty9 to 4.3.1, which includes jettty-9.4.48, which
has:
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.48.v20220622
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.47.v20220610
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.46.v20220331
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.45.v20220203
It also prepares for a new release.
=> (PE-34097) update tk-jetty9 to 4.3.1, prepare for release

CHANGELOG.md, project.clj
The rbac-client has been updated with a new version of parse-subject to normalize subjects when interacting with the rbac service.
=> (maint) Bump rbac-client to support updated parse-subject function

CHANGELOG.md, project.clj
This update to the postgres driver resolves CVE-2022-31197 as well
as adds support for 64K indexed parameters. The prior version only
supported 32K.
It also prepares for the subsequent release.
=> (PE-34255)  update postgres driver version to 42.4.1

CHANGELOG.md, project.clj
This update to the postgres driver resolves CVE-2022-31197 as well
as adds support for 64K indexed parameters. The prior version only
supported 32K.
This also prepares for the release in a separate commit.
=> (PE-34255) update postgres driver version to 42.4.1 

CHANGELOG.md, project.clj
Update honeysql v2 to latest. To upgrade PuppetDB from honeysql v1, we
need to use some of the postgres operators added in 2.2.891
=> (maint) Update honeysql (v2) to 2.3.911

CHANGELOG.md, project.clj
This commit adds a dependency on bouncycastle's TLS library. Previously, we were hard-coding the dependency version in each project that uses it. This allows us to manage the version centrally.
=> (PE-34579) Manage bctls

CHANGELOG.md, project.clj
In an effort to keep the bouncy-castle FIPS library versions up to date, this updates:
```
bcpkix-fips 1.0.6
bc-fips 1.0.2.3
bctls-fips 1.0.13
```
=> (maint) update bouncy-castle fips dependencies to the latest

CHANGELOG.md
This moves the unreleased changelog nodes under the 5.2.6 version.
=> (main) prepare for 5.2.6 release

CHANGELOG.md, project.clj
This updates:
* `trapperkeeper-webserver-jetty9` to `4.4.0`
* `trapperkeeper-metrics` to `1.5.0`
* `clj-http-client1` to `2.1.0`
* `dujour-version-check` to `1.0.0`
* `analytics-client` to `1.2.0`
in order to remve the dependency on the `15on` versions of the bouncycastle libraries, in favor of the `18on` versions.
It also prepares for a new release.
=> (maint) update dependencies, prepare for release

CHANGELOG.md, project.clj
This updates ssl-utils to the recently released `3.5.0` which changes the dependency on to the `18on` version of bouncycastle instead of the recently renamed `15on` series.
=> (maint) update ssl-utls, prepare for release

CHANGELOG.md, project.clj
This adds `stylefruits/gniazdo` to the set of dependencies managed with clj-parent. Several projects define the version of `stylefruits/gniazdo` used and this causes dependency conflicts downstream.
=> (PE-34652) add stylefruits/gniazdo 1.2.1 as a managed dependency

CHANGELOG.md, project.clj
This commit bumps the version of trapperkeeper-webserver-jetty9 to a version that makes use of the `stylefruits/gniazdo` version defined in this project, rather than pinning its own version.
=> (PE-34658) Bump tk-jetty9 to 4.4.1

CHANGELOG.md, project.clj
=> (maint) Bump rbac-client to support optional subject identity provider id

CHANGELOG.md, project.clj
This fixes a bug that prevented connection reuse when using an SSL
client certificate.
=> (maint) Update clj-http-client to 2.1.1

CHANGELOG.md, project.clj
Resolves https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-3038426
=> (PE-34664) Update jackson libraries to 2.14.0

CHANGELOG.md, project.clj
=> Fix ini4j CVE-2022-41404 and postgresql CVE-2022-41946

CHANGELOG.md, project.clj
Pending releasing jdbc-util 1.4.0 after https://github.com/puppetlabs/jdbc-util/pull/88/ is merged
=> (PE-35357) Upgrade Hikari CP to 5.x series

CHANGELOG.md, project.clj
Pending merge of https://github.com/puppetlabs/trapperkeeper/pull/306 and release of trapperkeeper 3.3.0
=> (PE-34726) Bump logback version to 1.3.5

CHANGELOG.md, project.clj
This reverts commit df4ce0ebe8778d8d314fdb8dfc7ff9c5094ace0c due to compatibility issue with logback 1.3.x.
=> Revert "(PE-34726) Bump logback version to 1.3.5"

CHANGELOG.md, project.clj
This updates tk-jetty9 to 4.4.2 that includes the latest version of jetty to address CVE-2023-26048.
=> (PE-35872) update trapperkeeper jetty 9 to 4.4.2

CHANGELOG.md, project.clj
In a previous commit [1], trapperkeeper-webserver-jetty9 was updated to v4.4.2 to address CVE-2023-26048 and CVE-2023-26049. That version was erroneously built with jdk11. This commit updates tk-webserver-j9 to a new release built with JDK8 to maintain compatibility with FOSS 7.x.
[1]: 224e551c31b2dc7e1166464e5f58a1b32bc9e672
=> (maint) update tk-webserver-j9 to v4.4.3

CHANGELOG.md, project.clj
=> (PE-34960) Update clj-parent with jruby 9.4 bump

CHANGELOG.md, project.clj
This updates the version to 6.x to correspond to the new jruby version which has compatibility for Ruby 3.
=> (maint) update version to 6.x series

CHANGELOG.md, project.clj
This updates logback to 1.2.12, which is the latest version in the 1.2 series to address issues with logging and jetty 10.
=> (PE-35979) bump logback to latest 1.2.x series

CHANGELOG.md, project.clj
This updates clj-kitchensink to bring in some new java.time conversion
functions since clj-time is deprecated, as is joda time.  Additionally
it adds a function for comparing version strings based on the puppet 'versioncmp'.
Finally clj-kondo and eastwood were applied and reflection issues
were addressed.
=> (maint) update kitchensink and prepare for release

CHANGELOG.md, project.clj
This updates trapperkeeper to 4.0 and removes clj-yaml which has
known security issues.
In a separate commit:  
This is a prep for the 7.0.0 release, which contains breaking changes
in trapperkeeper -- it removes support for yaml based configuration
files.
=> (PE-36370) update trapperkeeper to 4.0, remove clj-yaml ; prepare for release.

CHANGELOG.md, project.clj
This commit updates trapperkeeper-metrics and trapperkeeper-status to new versions that remove the use of ring-defaults and removes ring-defaults, which is no longer actively maintained.
Commits for that work in tk-metrics [1] and tk-status [2]
[1]: https://github.com/puppetlabs/trapperkeeper-metrics/commit/f5cf1040b7d8cbb8a5f4601b130ff60e6fb7153d
[2]: https://github.com/puppetlabs/trapperkeeper-status/commit/85a031c9d98a941e3160d1e1767bcf6942836fbe
=> (PE-36390) remove ring-defaults

CHANGELOG.md, project.clj
(PE-36390) remove ring-defaults
This commit updates trapperkeeper-metrics and trapperkeeper-status
to new versions that remove the use of ring-defaults and removes
ring-defaults, which is no longer actively maintained.
Commits for that work in tk-metrics [1] and tk-status [2]
[1]: f5cf1040b7d8cbb8a5f4601b130ff60e6fb7153d
[2]: 85a031c9d98a941e3160d1e1767bcf6942836fbe
=> (PE-36390) remove ring defaults, prepare for 7.0.1 release

CHANGELOG.md, project.clj
This updates jvm-ssl-utils to 3.5.1, which allows the addition of attributes to Certificate Signing Requests made through the "simple" namespace as well as a function to extract the attributes from the CSR.
Additionally, it updates the CHANGELOG in preparation for a new release.
=> (PE-36490) update jvm-ssl-utils, prepare for release

CHANGELOG.md, project.clj
This updates trapperkeeper to 3.3.1 to remove its dependency on clj-yaml.
In addition, this updates the changelog in preparation for release.
=> (PE-36476) update tk to 3.3.1 and prepare for release

CHANGELOG.md, project.clj
This updates snakeyaml to 1.3.3 to version 2.0 which resolves CVE-2022-1471
=> (maint) update snakeyaml to 2.0 from 1.3.3

CHANGELOG.md, project.clj
In two commits, this updates trapperkeeper-authorization to 2.0.1 to remove some unneeded verbose warnings, and to capture some dependency updates.  It also prepares for a new `z` release.
=> (PE-36775) update trapperkeeper-authorization and prepare for release

CHANGELOG.md, project.clj
We are very behind. JRuby has kept up to date and for our next update
want to move jruby-deps to use clj-parent. To prepare for this we should
update joda-time to the latest release.
=> (maint) Update joda-time

CHANGELOG.md, project.clj
The "y" version was bumped due to the removal of the old bouncy-castle library versions that aren't used anymore.
=> (maint) prepare for a new release 5.6.0

CHANGELOG.md, project.clj
This addresses two CVES: CVE-2023-36478 and CVE-2023-44487
=> (PE-36979) update trapperkeeper-jetty9 to 4.5.2

CHANGELOG.md, project.clj
This update addresses two CVEs: CVE-2023-36478 and CVE-2023-44487
=> (PE-36979) update tk-webserver-jetty9 to 4.5.2

CHANGELOG.md, project.clj
=> (maint) Update jruby-utils to bring in JRuby 9.3.11

CHANGELOG.md, project.clj
This updates clj-kitchensink to 3.2.4 and prepares for a new 7.2.7 version of clj-parent.
=> (maint) update kitchensink to 3.2.4, prepare for release

CHANGELOG.md, project.clj
Due to compatiblity issues with jetty9 and tk-metrics 2.0, the version of metrics needs to be rolled back to 1.5.1 and manually bumped in dependent projects until all the projects are using jetty10 and jetty9 can be removed.
=> (PE-35510) update tk-metrics back to 1.5.1

CHANGELOG.md, project.clj
=> (maint) Bump tk-jetty-10 to 1.0.5

CHANGELOG.md, project.clj
This updates jetty10 to 1.0.12, and prepares for another release.
=> (PE-37265) update jetty-10, prepare for release

CHANGELOG.md, project.clj
Waiting on the fix landing in tk-j10 and a new release of that.
=> (PE-34094) update tk-j10 to 1.0.14; prep for 7.2.18 release

CHANGELOG.md, project.clj
This updates logback to 1.3.14 to address CVE-2023-6378 / CVE-2023-6381
It also prepares for a release.
=> (PE-37321) update logback to 1.3.14, prepare for release

CHANGELOG.md, project.clj
=> (maint) Remove jetty9 dependencies, bump clj-parent y version

CHANGELOG.md, project.clj
This updates clj-kitchensink to 3.2.5 to address a potential writer leak in the `atomic-write` function if the `write-function` throws an exception.
=> (maint) update clj-kitchensink to 3.2.5

CHANGELOG.md, project.clj
=> (PE-37293) Bump tk-jetty to 1.0.16 to add debug logging

CHANGELOG.md, project.clj
This adds the apache license block to the project.clj to allow it to be properly published to clojars.
=> (maint) add license to project.clj

CHANGELOG.md, project.clj
This updates http-client to 2.1.2, to provide support for multiple `Set-Cookie` headers in a response. The response contains the headers in a map, which prevents multiple `Set-Cookie` headers individually, so they are compbined together in one entry separated by newlines.
This also preparse for the 7.3.4 release
=> (PE-37455) update http-client to 2.1.2, prepare for release

CHANGELOG.md, project.clj
This addresses some issues with potential race conditions in websockets.
It also prepares for a release.
=> (PE-37632) update jetty 10 to 10.0.20

CHANGELOG.md, project.clj
This updates webserver-jetty-10 to 1.0.18 to add some websocket
client dependencies to allow the jetty version to be centrally
managed.
=> (PE-37632) update webserver-jetty-10 to 1.0.18

CHANGELOG.md, project.clj
This updates trapperkeeper metrics to 2.0.3 so that it uses clj-parent
for determining the version of tk-ws-jetty10 to include.
=> (PE-37632) update trapperkeeper metrics to 2.0.3

CHANGELOG.md, project.clj
=> (PE-37632) update trapperkeeper-status to 1.2.0, prepare for release

CHANGELOG.md, project.clj
This addresses [CVE-2024-1597](https://github.com/pgjdbc/pgjdbc/security/advisories/GHSA-24rp-q3w6-vc56)
=> (PE-37762) update postgres to 42.7.2

CHANGELOG.md, project.clj
This addresses https://github.com/advisories/GHSA-xfg6-62px-cxc2.
=> (PE-37762) update Postgres to 42.4.4

CHANGELOG.md, project.clj
This adds the license entry to project.clj to allow it to be published on clojars.  It also adjusts the changelog to indicate that 5.6.8 wasn't properly released.
=> (maint) add license entry, prepare for release

CHANGELOG.md, project.clj
This updates `org.apache.commons/commons-exec` to `1.26.0` to address CVE-2024-25710 CVE-2024-26308 and CVE-2023-42503
It also updates `org.apache.commons/commons-lang3` to `3.14.0` as the previous version was released in 2014.
It also updates `org.apache.commons/commons-exec` to the latest version `1.4.0`
=> (PE-37763) update commons-compress to 1.26, commons-exec, commons-lang3

CHANGELOG.md, project.clj
This updates `org.apache.commons/commons-exec` to `1.26.0` to address CVE-2024-25710 CVE-2024-26308 and CVE-2023-42503
=> (PE-37763) update commons-compress to 1.2.6

CHANGELOG.md, project.clj
apache-compress 1.26.0 (COMPRESS-632) moved to using a FileTimes class
in commons-io that was added to commons-io in 2.12.0.
=> Update commons-io to 2.15.1

CHANGELOG.md, project.clj
This updates clj-http-client to 2.1.3 to allow for correct 204 handling
in the unbuffered stream client.
=> (maint)  update clj-http-client to 2.1.3

CHANGELOG.md, project.clj
This updates `host-action-collector-client` to `0.1.5` which brings in handling for `nil` status results from requests, and specific logging for documenting the cause of those cases.
=> (maint) update host-action-collector-client to 0.1.5

CHANGELOG.md, project.clj
Resolved a bug in pgjdbc
https://github.com/pgjdbc/pgjdbc/issues/3014
which resulted in a failure in PuppetDB due to
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer
=> (PDB-5730) Update pgjdbc to 42.4.5

CHANGELOG.md, project.clj
=> (PE-37186) update host-action-collector-client to 0.1.6

CHANGELOG.md, project.clj
This updates clj-kitchensink which adds new time functions that
can be used to parse Puppet durations, and will aid with the move
away from clj-time.
=> (maint) update clj-kitchensink to 3.0.0

CHANGELOG.md, project.clj
Bumping kitchensink for 5.x for time parsing function in https://github.com/puppetlabs/clj-kitchensink/pull/132.
Although we aren't removing clj-time in 2021.7.x, might as well keep the work for https://perforce.atlassian.net/browse/PE-38243 consistent for 2021.7.x and main.
=> (maint) Bump kitchensink to 3.3.1

project.clj
This commit updates jdbc-util to 1.4.3, which brings in a new version that was built against the dependencies on clj-parent 5.6.15 which has and updated version of pgjdbc. While we were not shipping a vulnerable version of pgjdbc since that was up-to-date in clj-parent, the dep in jdbc-util was still triggering the mend scans.
=> (PE-37972) update jdbc-util to 1.4.3

CHANGELOG.md
=> (maint) prepare for 5.6.16 release

.github/workflows/mend.yml
This updates the version of twingate, java, clojure and the checkout actions to be the latest versions.
=> (maint) update action versions

CHANGELOG.md, project.clj
This version conditionalizes some potentially expensive logging
when there are a lot of events generated.
=> (maint) update trapperkeeper-filesystem-watcher to 1.2.3 

CHANGELOG.md, project.clj
This improves the performance when debug logging is disabled. In addition it makes shutdown more robust, catching additional exceptions and ensuring that futures are correctly cancelled on shutdown.
=> (maint) update trapperkeeper-filesystem-watcher to 1.2.4

CHANGELOG.md, project.clj
See https://github.com/puppetlabs/trapperkeeper/pull/313 for details on`logged?` change.
=> (maint) Bump tk-version for `logged?` changes

CHANGELOG.md, project.clj
This fixes an issue with a potential stack overflow when large
number of file system events are being processed. It also adds
specific interfaces to allow watchers to register for changes in
specific files, rather than handling all events and filtering out
the ones that aren't interesting.
In a separate commit, it prepares for release.
=> (PE-38421) update trapperkeeper-file-system-watcher to 1.2.5

CHANGELOG.md, project.clj
This updates the client to ensure that data files are not written with execute permissions.
=> (PE-38476) update host-action-collector-client to 0.1.8

CHANGELOG.md, project.clj
=> (PE-38477) update kitchensink to 3.4.0 for java.time encoders

CHANGELOG.md, project.clj
=> (maint) update to trapperkeeper 3.3.3, prepare for release

CHANGELOG.md, project.clj
=> (maint) update trapperkeeper to 4.0.2

CHANGELOG.md, project.clj
tag: https://github.com/puppetlabs/jruby-utils/releases/tag/5.2.0
=> (PE-38292) Upgrade to JRuby 9.4.8.0

CHANGELOG.md, project.clj
This updates ring-middleware to 2.0.3 which adds some new standard
wrappers and optimizes the uncaught exception handler.
It also prepares for a new release.
=> (PE-38702) update ring-middleware, prepare for release

CHANGELOG.md, project.clj
This updates the wrap-uncaught-errors to include the method and uri in the log message to aid debugging of the issue raised by the exception.
=> (PE-38702) update ring-middleware to 2.0.4, prepare for release

CHANGELOG.md, project.clj
=> (maint) Revert back to JRuby 9.3.14
