puppetlabs/clj-parent

project.clj

Update the versions of commons-code and ring-servlet to match the
uses in other projects.

(maint) update commons-codec and ring-servlet

---

CHANGELOG.md
project.clj

Also update the changelog in preparation for 0.5.1 release.

Merge up 0.4.x to master 22march2017

---

CHANGELOG.md
project.clj

Adds a stream->sha256 function.

(SERVER-1993) Update clj-kitchensink to 2.5.1, tk to 1.5.3

---

project.clj

Adding clj-ldap common version.

(PE-16279) Adding clj-ldap

---

CHANGELOG.md
project.clj

This updates jdbc-util to 1.2.3 and the changelog.

(PE-24859) update jdbc-util to 1.2.3

---

project.clj

Add the bouncycastle jars to the managed-dependencies.

(PDB-4357) support using bouncy castle FIPS

---

CHANGELOG.md
project.clj

```
Conflicts:
- CHANGELOG.md
- project.clj
```

(PE-27458) Merge branch '1.7.x' into '2.7.x'

---

CHANGELOG.md

```
Conflicts:
- CHANGELOG.md
- project.clj
```
No real changes, just housekeeping.

(maint) Merge branch '3.1.x' into 'master'

---

CHANGELOG.md
project.clj

Mergeup17x

---

CHANGELOG.md
project.clj

Mergeup27x

---

CHANGELOG.md
project.clj

Mergeup31x

---

CHANGELOG.md
project.clj

Update jruby-utils and trapperkeeper

---

project.clj

This reverts commit 59ec12298d5fd9442ada6c94d7bc3f317cf63d12.

(maint) Revert release repo to clojars

---

CHANGELOG.md
project.clj

Test merge 1.7x -> master

---

CHANGELOG.md
project.clj

(maint) bump clj-ldap version to latest

---

CHANGELOG.md
project.clj

(SERVER-2799) Dependency bumps for puppetserver 6.12

---

CHANGELOG.md
project.clj

(maint) Update pgjdbc driver to 4.2.14

---

CHANGELOG.md
project.clj

(maint) update prismatic schema to latest (1.1.12)

---

CHANGELOG.md
project.clj

Update snakeyaml to 1.27, clj-yaml to 0.7.2, tk-jetty9 to 4.1.2, and tk-metrics to 1.4.0

---

CHANGELOG.md
project.clj

(PE-31797) Update tk-jetty9 to 4.1.6

---

CHANGELOG.md

(maint) update changelog for 4.6.22

---

README.md

This commit updates the README to set expectations for contributing.

(maint) Update README

---

CHANGELOG.md

(maint) Prep for 4.6.25 release

---

CHANGELOG.md

Update changelog in prep for release.

(maint) prep for 4.8.4 release

---

.github/workflows/snyk.yml

This PR adds the snyk clojure GitHub action. All required secrets have already been provisioned.

add snyk github action

---

LICENSE

We license our open source software under the Apache 2 license.

(maint) Add LICENSE file

---

CHANGELOG.md

(maint) prep for 4.9.6 release

---

project.clj

In anticipation of breaking changes, and the creation of the 4.x branch, this moves the main branch to 5.0.0

(maint) move main to 5.0.0 series

---

CHANGELOG.md

(PE-33852) update changelog in preparation for release

---

CODEOWNERS

(PE-33913) change codeowners to dumpling

---

CHANGELOG.md
project.clj

See individual commit descriptions.

(PE-34578) add bouncycastle with jdk8 and up support

---

CHANGELOG.md
project.clj

See individual commit messages.

(PE-34578) roll bc on18 back to 1.71

---

CHANGELOG.md
project.clj

(SERVER-3230) Update JRuby to 9.3.9.0 via jruby-utils 4.0.3

---

CHANGELOG.md
CODEOWNERS

(maint) Fix changelog to reflect 5.2.16 release

---

CHANGELOG.md
project.clj

(PE-36185) Update logback version to 1.3.7, update deps

---

CHANGELOG.md
project.clj

(PE-36481) Retain trapperkeeper version 3.3.1

---

CHANGELOG.md

Update CHANGELOG.md for 5.5.1

---

CHANGELOG.md
project.clj

(PE-36842) update jetty9 version

---

CHANGELOG.md
project.clj

(PE-36367) Update bouncycastle versions, remove jdk15on jars

---

CHANGELOG.md
project.clj

(maint) Update joda-time

---

CHANGELOG.md
project.clj

(PE-36860) fix tagged cert stack overflow

---

CHANGELOG.md
project.clj

(PE-36375) Update jruby-utils to bring in JRuby 9.4.3

---

CHANGELOG.md

(maint) release prep for 5.6.5

---

CHANGELOG.md

(PE-36375) Release prep for 7.2.5

---

CHANGELOG.md
project.clj

(PE-35509) Add trapperkeeper-webserver-jetty10, tk-metrics 2.0.0

---

CHANGELOG.md
project.clj

(PE-34094) update tk jetty10 to v1.0.11

---

project.clj

(maint) add host-action-collector-client

---

CHANGELOG.md
project.clj

(PE-37886) [5.x] Update Clojure version to 1.11.2

---

CHANGELOG.md
project.clj

(PE-37886) Update Clojure version to 1.11.2

---

CHANGELOG.md

(maint) prepare for 7.3.18 release

---

CHANGELOG.md
project.clj

(maint) Upgrade jruby 9.3.11

---

CHANGELOG.md
project.clj

(maint) Take up jruby-utils and JRuby 9.4.7

---

CHANGELOG.md

(maint) Deduplicate CHANGELOG entry

---

CHANGELOG.md
project.clj

(maint) update clj-shell-utils to 2.0.1

---

CHANGELOG.md
project.clj

(maint) Roll back latest jruby-utils bump

---

CHANGELOG.md
project.clj

(PE-37376) Take up improved JRuby instance creation

---

CHANGELOG.md
project.clj

(PE-38292) Upgrade to JRuby 9.3.15.0
